FROM registry.saas.hand-china.com/hap-cloud/base:latest
ADD test4.jar test4.jar
CMD java -jar test4.jar $MYSQL_IP $MYSQL_PORT $MYSQL_DATABASES $MYSQL_USER  $MYSQL_ROOT_PASSWORD
                        $title $description